# Name of the workflow. You can give any name
name: StudentManagement CI

on:
  # Run CI when code is pushed to main or any feature branch
  push:
    branches:
      - master
      - feature/**
  
  # Run CI when a pull request is created or updated for main
  pull_request:
    branches:
      - master

# A job is a group of steps. its internal key name is: build-test-publish
# display name is Build, Test, and Publish which is visible to user
# it will run on a machine which is a Linux machine ubuntu
jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

# attach the environment  
    environment:
      name: Development
      deployment: false
  
    # steps are the works or tasks done inside a job
    steps:
      # Step 1: Download the repository code 
      - name: Checkout source code
        uses: actions/checkout@v5

      # Step 2: Install .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

       # show repo name  
      - name: show repository name
        run: echo "workflow environment is ${{vars.SERVER}}"

        #show target server
      - name: show target name  
        run: echo "target server is ${{secrets.DEP}}"


      - name: check repo secret
        env:
          Demo: ${{secrets.DEMO_API_KEY}}
        run: |
           if[-z "$Demo"]; then
              echo "Repositor secret Demo us missing"
              exit 1
            fi
            echo "Repository secret is available"

      # check environment level secret
      - name: check envirom secret
        env:
          deploy: ${{secrets.DEP}}
        run: |
            if[-z "$deploy"]; then
              echo "environment secret is missing"
              exit 1
            fi
            echo "Environment secret is available"
              
      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore studentManagement.slnx

      # Step 4: Build the solution in Release mode
      - name: Build solution
        run: dotnet build studentManagement.slnx --configuration Release --no-restore

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test studentManagement.slnx --configuration Release --no-build --verbosity normal

      # Step 6: Publish the API project
      - name: Publish Web API
        run: dotnet publish studentManagement/studentManagement.csproj --configuration Release --output ./publish --no-build

      # Step 7: Store the publish output as an artifact
      - name: Upload publish artifact
        uses: actions/upload-artifact@v6
        with:
          name: studentmanagement-api-publish
          path: ./publish
